

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sessionone
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DBSettings : DbContext
{
    static DBSettings _context;

    static public DBSettings getInstance()
    {
        if (_context == null)
        {
            _context = new DBSettings();
        }
        return _context;
    }
public DBSettings()
        : base("name=DBSettings")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Countries> Countries { get; set; }

    public virtual DbSet<ExitCauses> ExitCauses { get; set; }

    public virtual DbSet<Offices> Offices { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<TrafficViewer> TrafficViewer { get; set; }

    public virtual DbSet<Users> Users { get; set; }

}

}

